name: Release

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java 8
        uses: actions/setup-java@v1
        with:
          java-version: '8'
      - name: Init Properties
        run: 'echo "$GRADLE_PROPERTIES" > insta-bot-backend/gradle.properties'
        env:
          GRADLE_PROPERTIES: ${{secrets.GRADLE_PROPERTIES}}
      - name: Build Plugin
        run: ./gradlew jib
        env:
          GRADLE_OPTS: -Dorg.gradle.daemon=false
      - name: test
        run: ls